export const scaleFactor = 4;

export const dialogueData = {
    pc: `I spend a lot of time here, more than I probably should. I work mostly in JavaScript. I've made a couple of projects with vanilla JavaScript and with other technologies that are part of the JavaScript ecosystem, like React, Express, and Node.js. I also have developed small programs in C. Currently, I'm dedicating a lot of time to perfect my React and TypeScript skills. I'm also enrolled in a web programming course, where I'm covering topics like software methodologies, software engineering, programming algorithms and scripts, etc. Anyway regardless of the language, I just like programming. Here is my <a href="https://github.com/DiogoCoelho98" target="_blank">Github</a>!`,
    certificate: 'This is where I hang my certificates. Sometimes when I need extra motivation, I like to look at them and think about the projects I already created, which gives me the boost I need. A curiosity about me is the fact that besides the online and in-person web development certificates, I also possess a degree in Physical Education and Sports. Check my LinkedIn to learn more about my education path <a href="https://www.linkedin.com/in/diogo-borges-coelho/" target="_blank">LinkedId.</a>',
    "sofa-table": `I like to relax here with my 3 legged dog and watch YouTube. I've been watching tech YouTubers a lot recently like the <a href="https://www.youtube.com/@ThePrimeTimeagen" target="_blank">Theprimeagen</a>.`,
    tv: `Usually, I don't spend a lot of time watching TV. I tend to prefer to spend my free time doing other activities, like training, hiking, trying local food, and going to concerts.`,
    bed: `I am a morning person, so I try to get to bed as early as I can. Usually, this is where I think about my plans for future apps. This is probably not the best approach, but we all have flaws, right?`,
    resume: `Ohhh look my resume! <a href="https://github.com/DiogoCoelho98/Resume/blob/main/Diogo_Coelho_CV.pdf" target="_blank"> Why don't you give it a look?</a><a href= "mailto: diogocoelho19988@gmail.com"> Click to send me an email</a> if you have any interesting job opportunities!`,
    projects: `Info about this portfolio : It's made with the Kaboom.js library which is a library for making games in JavaScript.
    Text is rendered with HTML/CSS. So the textbox you're currently reading is not rendered within canvas. Learn more about how to use
    Kaboom.js by watching some of my tutorials <a href="https://youtube.com/@jslegenddev" target="_blank">here</a>.`,
    library: `There are a lot of books on my shelves. I like to read about sports methodologies and training periodization. Stoicism, samurais, programming, and some other topics. You can also find books in Portuguese, my first language.`,
    exit: `If you want to leave my portfolio, just close the tab.`,
  };